### ISSUE TITLE
"there's internal problem" pop-up on AICP

### ISSUE THREAD

**Issue by MikuDroid** [Genom-Project/android_kernel_xiaomi_ginkgo#4]
Latest test build causes wifi cannot be turned on on AICP rom (it's a test build duh), how can i provice some logs if it necessary?

**Comment by MikuDroid** [comment]
Wifi seems to be fixed in latest AICP rom, but i got "there's internal problem" pop up after booted into system.

**Comment by ramabondanp** [comment]
should be fixed on latest build
